CALL BUILD_01SETCONST.BAT
CALL BUILD_02PREPARE.BAT
CD %FOLDER_ISS%\%FOLDER_AMUNHOTEP%
FOR %%I IN (AMUNHOTEP__*.ISS) DO %ISS% %%I >%FOLDER_ISSLOG%\%SUFFIX%_%%~nI.LOG
CD %FOLDER_ISS%
RD /S /Q %FOLDER_ISSETHALON%