SET SUFFIX=%TIME:~0,-6%
SET SUFFIX=%SUFFIX::=%
SET SUFFIX=%SUFFIX: =0%
SET SUFFIX=%DATE:~-4%%DATE:~3,2%%DATE:~0,2%_%SUFFIX%
SET FOLDER_APPL=d:\appl
SET FOLDER_AMUNHOTEP=amunhotep
SET FOLDER_FIREBIRD=firebird
SET FOLDER_GIT=git
SET FOLDER_IBEXPERT=ibexpert
SET FOLDER_PEAKTOP=peaktop
SET FOLDER_PHP=php
SET FOLDER_APACHE24=apache24
SET FOLDER_WWWROOT=www
SET FOLDER_ISS=d:\projects\iss
SET FOLDER_ISSLOG=%FOLDER_ISS%\$LOGS
SET FOLDER_ISSETHALON=%FOLDER_ISS%\$ETHALON
SET URL_AMUNHOTEPLIB="https://github.com/amunhotep/lib.git"
SET GIT=%FOLDER_APPL%\%FOLDER_GIT%\bin\git.exe
SET GITR=%GIT% clone 
SET ISS=%FOLDER_APPL%\inno\5.5.9\iscc.exe
SET CP1=COPY /Y
SET CP=XCOPY /Y /F
SET CPR=%CP% /S /E /H /R