CALL BUILD_01SETCONST.BAT
CD %FOLDER_ISS%
IF NOT EXIST "%FOLDER_ISSETHALON%" MD "%FOLDER_ISSETHALON%"
IF NOT EXIST "%FOLDER_ISSLOG%" MD "%FOLDER_ISSLOG%"
CD %FOLDER_ISSETHALON%
IF NOT EXIST %FOLDER_FIREBIRD% MD %FOLDER_FIREBIRD%
IF NOT EXIST %FOLDER_IBEXPERT% MD %FOLDER_IBEXPERT%
IF NOT EXIST %FOLDER_PEAKTOP% MD %FOLDER_PEAKTOP%
IF NOT EXIST %FOLDER_GIT% MD %FOLDER_GIT%
IF NOT EXIST %FOLDER_PHP% MD %FOLDER_PHP%
IF NOT EXIST %FOLDER_APACHE24% MD %FOLDER_APACHE24%
IF NOT EXIST %FOLDER_WWWROOT% MD %FOLDER_WWWROOT%
%CPR% %FOLDER_APPL%\%FOLDER_FIREBIRD%\* %FOLDER_ISSETHALON%\%FOLDER_FIREBIRD%\*
%CPR% %FOLDER_APPL%\%FOLDER_IBEXPERT%\* %FOLDER_ISSETHALON%\%FOLDER_IBEXPERT%\*
%CPR% %FOLDER_APPL%\%FOLDER_GIT%\* %FOLDER_ISSETHALON%\%FOLDER_GIT%\*
%CPR% %FOLDER_APPL%\%FOLDER_PHP%\7.2.11\* %FOLDER_ISSETHALON%\%FOLDER_PHP%\*
%CPR% %FOLDER_APPL%\apache\2.4.35\* %FOLDER_ISSETHALON%\%FOLDER_APACHE24%\*
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%
IF NOT EXIST bin MD bin
IF NOT EXIST conf MD conf
IF NOT EXIST data MD data
IF NOT EXIST fonts MD fonts
IF NOT EXIST lib MD lib
IF NOT EXIST tmp MD tmp
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\bin
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\bin\amunhotep.exe amunhotep.exe
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\bin\midas.dll midas.dll
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\bin\peaktop00040*.dll peaktop00040*.dll
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\bin\peaktop100421.dll peaktop100421.dll
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\conf
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\amunhotep.ps amunhotep.ps
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\amunhotep_start*.conf amunhotep_start*.conf
%CP1% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\amunhotep_msg.*.conf amunhotep_msg.*.conf
IF NOT EXIST bmp MD bmp
IF NOT EXIST code MD code
IF NOT EXIST ent MD ent
IF NOT EXIST icons MD icons
%CPR% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\bmp\* %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\conf\bmp\*
%CPR% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\code\* %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\conf\code\*
%CPR% %FOLDER_APPL%\%FOLDER_PEAKTOP%\conf\icons\* %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\conf\icons\*
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\data
IF NOT EXIST backup MD backup
IF NOT EXIST bat MD bat
IF NOT EXIST logs MD logs
IF NOT EXIST sql MD sql
IF NOT EXIST tmp MD tmp
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\data\logs
IF NOT EXIST backup MD backup
IF NOT EXIST restore MD restore
IF NOT EXIST upload MD upload
IF NOT EXIST download MD download
IF NOT EXIST update MD update
IF NOT EXIST reindex MD reindex
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\fonts
%CPR% %FOLDER_APPL%\%FOLDER_PEAKTOP%\fonts\* %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\fonts\*
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\lib
%GITR% %URL_AMUNHOTEPLIB% %FOLDER_AMUNHOTEP%
CD %FOLDER_ISSETHALON%\%FOLDER_PEAKTOP%\lib\%FOLDER_AMUNHOTEP%
ATTRIB -H /S /D .git
CD %FOLDER_ISS%\%FOLDER_AMUNHOTEP%