CALL BUILD_01SETCONST.BAT
CALL BUILD_02PREPARE.BAT >%FOLDER_ISSLOG%\%SUFFIX%_%FOLDER_AMUNHOTEP%_PREPARE.LOG
%ISS% amunhotep__th001.iss >%FOLDER_ISSLOG%\%SUFFIX%_amunhotep__th001.LOG
CD %FOLDER_ISS%
RD /S /Q %FOLDER_ISSETHALON%