SET PREFIX=RS_005
SET DIR_DB=D:\appl\peaktop\data
SET DIR_BACKUP=D:\appl\peaktop\data\backup
SET DIR_BACKUPTMP=D:\appl\peaktop\data\tmp
SET GBAK=D:\APPL\FIREBIRD\BIN\GBAK.EXE -B -G -TRANSPORTABLE -IGNORE -LIMBO -V -USER SYSDBA -PASSWORD "masterkey"
SET ZIP="C:\Program Files\7-Zip\7Z.EXE" A -t7z 
SET SUFFIX=%TIME:~0,-6%
SET SUFFIX=%SUFFIX::=%
SET SUFFIX=%SUFFIX: =0%
SET SUFFIX=%DATE:~-4%%DATE:~3,2%%DATE:~0,2%_%SUFFIX%
CD %DIR_DB%
FOR %%I IN (*.FDB) DO COPY /Y %%I %DIR_BACKUPTMP%\%%I
CD %DIR_BACKUPTMP%
FOR %%I IN (*.FDB) DO %GBAK% %%I %DIR_BACKUPTMP%\%%I.FBK -Y %DIR_BACKUPTMP%\%%I.LOG
CD %DIR_BACKUPTMP%
%ZIP% %DIR_BACKUPTMP%\%PREFIX%_%SUFFIX%.7Z %DIR_BACKUPTMP%\*.*
COPY /Y %DIR_BACKUPTMP%\%PREFIX%_%SUFFIX%.7Z %DIR_BACKUP%\%PREFIX%_%SUFFIX%.7Z
ERASE /F/Q %DIR_BACKUPTMP%\*.*
CD %DIR_BACKUP%